# Generated by Django 6.0.6 on 2026-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.URLField(max_length=600)),
                ('shorturl', models.URLField(max_length=250)),
                ('uuid_field', models.UUIDField()),
            ],
        ),
    ]
